SELECT DISTINCT(CITY) FROM STATION
WHERE SUBSTR(LOWER(CITY),1,1) NOT IN ('a','e','i','o','u')
OR
SUBSTR(LOWER(CITY),-1,1) NOT IN ('a','e','i','o','u');


-- SELECT DISTINCT(CITY) FROM STATION
-- WHERE CITY REGEXP '^[^aeiou]'
-- OR
-- CITY REGEXP '[^aeiou]$';
